### PR TITLE
Make toggleCalendar method return true on opening

### PR DESCRIPTION
**Pull request by xuhcc**
So we can use it like that:

```js
const opened = datepicker.toggleCalendar()
if (opened) {
    ...
}
```

### CODE REVIEW

**Comment by kekeh** [comment]
You can use **calendarToggle** callback: https://github.com/kekeh/angular-mydatepicker#calendartoggle-callback

Example: https://github.com/kekeh/angular-mydatepicker/wiki/calendarToggle-callback

**Comment by xuhcc** [comment]
I know, but I would prefer to use returned value as it better suits my needs.

**Comment by kekeh** [comment]
Ok. I merged this PR. Install latest version from npm. 

The return value only indicates was the operation open or close. The close operation is always asychronous if calendar animations are used so in that case the **toggleCalendar()** may return before the calendar has closed.

**Comment by xuhcc** [comment]
Thanks!

**Pull request merged**
